# Your Website Title
title: Hello World

# Your Website URL
url: 'http://jekyll-for-everyone.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Hello World
tagline: Eat, Sleep, Play, Rave
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Eat, Sleep, Play, Rave
description_tiny: 'Home: GMT+8 | Work: GMT-8'
email: hello.world@gmail.com
website: www.google.com # do not add http://
linkedin: your_linkedin
github: your_github
twitter: '@your_twitter'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm